name: nitish-dalvi

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://nitish-dalvi --delete
          aws s3 cp ./build/index.html s3://nitish-dalvi/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html
          aws s3 cp ./build/static/css/ s3://nitish-dalvi/static/css/ --recursive --metadata-directive REPLACE --cache-control max-age=31536000,public --content-type text/css
          aws s3 cp ./build/static/js/ s3://nitish-dalvi/static/js/ --recursive --metadata-directive REPLACE --cache-control max-age=31536000,public --content-type application/javascript
